In [90]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [91]:
df = pd.read_csv('/content/datalab_export_2026-05-29 00_14_28.csv')

In [92]:
df

,index,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
0,0,1,debt_consolidation,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0,0
1,1,1,credit_card,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0,0
2,2,1,debt_consolidation,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0,0
3,3,1,debt_consolidation,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0,0
4,4,1,credit_card,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,1,debt_consolidation,0.0775,156.11,10.714418,5.00,762,2131.000000,1359,5.6,2,0,0,0
96,96,1,debt_consolidation,0.1154,329.95,12.323856,20.00,727,10292.000000,107501,44.8,2,0,0,0
97,97,1,all_other,0.0807,313.67,12.061047,0.72,787,8010.000000,3054,5.6,3,0,0,0
98,98,1,all_other,0.0807,297.99,11.407565,2.44,792,8717.958333,40384,9.6,0,0,0,0
99,99,1,home_improvement,0.0933,239.65,11.440355,9.66,792,4529.000000,128000,0.0,3,0,0,0

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              100 non-null    int64
 1   credit.policy      100 non-null    int64
 2   purpose            100 non-null    object
 3   int.rate           100 non-null    float64
 4   installment        100 non-null    float64
 5   log.annual.inc     100 non-null    float64
 6   dti                100 non-null    float64
 7   fico               100 non-null    int64
 8   days.with.cr.line  100 non-null    float64
 9   revol.bal          100 non-null    int64
 10  revol.util         100 non-null    float64
 11  inq.last.6mths     100 non-null    int64
 12  delinq.2yrs        100 non-null    int64
 13  pub.rec            100 non-null    int64
 14  not.fully.paid     100 non-null    int64
dtypes: float64(6), int64(8), object(1)
memory usage: 11.8+ KB

In [94]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
index,100.0,49.500000,29.011492,0.000000,24.750000,49.500000,74.250000,99.000000
credit.policy,100.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
int.rate,100.0,0.101028,0.023150,0.071400,0.080700,0.096400,0.115400,0.159600
installment,100.0,227.940000,162.367679,32.550000,124.745000,160.615000,301.910000,829.100000
log.annual.inc,100.0,11.079282,0.715795,8.987197,10.596635,11.156251,11.512925,12.429216
dti,100.0,9.035000,5.981154,0.000000,3.662500,8.310000,14.395000,22.090000
fico,100.0,726.600000,44.854873,627.000000,682.000000,722.000000,763.250000,812.000000
days.with.cr.line,100.0,4562.093750,2630.856598,1110.000000,2684.968750,4253.979166,5840.000000,14008.958330
revol.bal,100.0,17009.490000,22933.459903,0.000000,3141.750000,6678.500000,22254.500000,128000.000000
revol.util,100.0,35.500000,26.172370,0.000000,14.300000,31.550000,53.650000,93.400000
inq.last.6mths,100.0,0.770000,1.033333,0.000000,0.000000,0.000000,1.000000,4.000000
delinq.2yrs,100.0,0.130000,0.393251,0.000000,0.000000,0.000000,0.000000,2.000000
pub.rec,100.0,0.060000,0.238683,0.000000,0.000000,0.000000,0.000000,1.000000
not.fully.paid,100.0,0.100000,0.301511,0.000000,0.000000,0.000000,0.000000,1.000000

In [95]:
df.isna().sum()

index                0
credit.policy        0
purpose              0
int.rate             0
installment          0
log.annual.inc       0
dti                  0
fico                 0
days.with.cr.line    0
revol.bal            0
revol.util           0
inq.last.6mths       0
delinq.2yrs          0
pub.rec              0
not.fully.paid       0
dtype: int64

In [96]:
df['purpose'].unique()

array(['debt_consolidation', 'credit_card', 'all_other',
       'home_improvement', 'small_business', 'major_purchase',
       'educational'], dtype=object)

In [97]:
df = pd.get_dummies(df, columns=['purpose'], drop_first=True, dtype=int)

df.columns.tolist()

['index',
 'credit.policy',
 'int.rate',
 'installment',
 'log.annual.inc',
 'dti',
 'fico',
 'days.with.cr.line',
 'revol.bal',
 'revol.util',
 'inq.last.6mths',
 'delinq.2yrs',
 'pub.rec',
 'not.fully.paid',
 'purpose_credit_card',
 'purpose_debt_consolidation',
 'purpose_educational',
 'purpose_home_improvement',
 'purpose_major_purchase',
 'purpose_small_business']

In [98]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [99]:
X = df.drop(columns=['index', 'credit.policy', 'not.fully.paid'])

In [100]:
y = df['not.fully.paid']

In [101]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [102]:
scaler = StandardScaler()

In [103]:
X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [110]:
model = LogisticRegression(class_weight='balanced', C=1.0, solver='liblinear', random_state=42)

In [111]:
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print(confusion_matrix(y_test, y_pred))
print()

print(classification_report(y_test, y_pred, zero_division=0))

[[10  7]
 [ 0  3]]

              precision    recall  f1-score   support

           0       1.00      0.59      0.74        17
           1       0.30      1.00      0.46         3

    accuracy                           0.65        20
   macro avg       0.65      0.79      0.60        20
weighted avg       0.89      0.65      0.70        20

In [106]:
from sklearn.model_selection import GridSearchCV

In [107]:
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear', 'saga']
}

log_reg = LogisticRegression(class_weight='balanced', random_state=42, max_iter=10000)

grid_search = GridSearchCV(
    estimator=log_reg,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1
)

grid_search.fit(X_train_scaled, y_train)

print(grid_search.best_params_)

best_model = grid_search.best_estimator_

{'C': 0.001, 'penalty': 'l1', 'solver': 'saga'}

In [108]:
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score

In [109]:
y_pred = best_model.predict(X_test_scaled)

y_pred_proba = best_model.predict_proba(X_test_scaled)[:, 1]

print(confusion_matrix(y_test, y_pred))
print()

print(classification_report(y_test, y_pred, zero_division=0))
print()

print(roc_auc_score(y_test, y_pred_proba))

[[17  0]
 [ 3  0]]

              precision    recall  f1-score   support

           0       0.85      1.00      0.92        17
           1       0.00      0.00      0.00         3

    accuracy                           0.85        20
   macro avg       0.42      0.50      0.46        20
weighted avg       0.72      0.85      0.78        20


0.5